"use client";

import { useEffect, useRef, useState } from "react";
import type { ApiDraft } from "@/lib/types";

type LiveDraft = ApiDraft & { liveBodyText: string };

export function DraftRow({
  draft,
  checked,
  onToggle,
}: {
  draft: ApiDraft;
  checked: boolean;
  onToggle: () => void;
}) {
  const [live, setLive] = useState<LiveDraft | null>(null);
  const [loading, setLoading] = useState(true);

  // Same defensive re-assertion as EnquiryCard's checkbox — see the comment
  // there for why this is needed, not just belt-and-suspenders.
  const checkboxRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    if (checkboxRef.current) checkboxRef.current.checked = checked;
  });

  useEffect(() => {
    let ignore = false;
    async function load() {
      const res = await fetch(`/api/drafts/${draft.id}`);
      const data = await res.json();
      if (!ignore) {
        setLive(data.draft ?? null);
        setLoading(false);
      }
    }
    load();
    return () => {
      ignore = true;
    };
  }, [draft.id]);

  return (
    <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm">
      <div className="flex items-start gap-3">
        <input
          ref={checkboxRef}
          type="checkbox"
          checked={checked}
          onChange={onToggle}
          autoComplete="off"
          data-1p-ignore
          data-lpignore="true"
          className="mt-1 h-4 w-4"
          aria-label={`Select draft to ${draft.toEmail}`}
        />
        <div className="flex-1">
          <p className="text-xs text-gray-400">
            Generated by {draft.generatedByUser.name} · {new Date(draft.generatedAt).toLocaleString()}
          </p>
          {loading ? (
            <p className="mt-2 text-sm text-gray-400">Loading exact text from Gmail…</p>
          ) : (
            <div className="mt-2 space-y-1 text-sm">
              <p>
                <span className="font-medium text-gray-500">To: </span>
                {live?.toEmail ?? draft.toEmail}
              </p>
              <p>
                <span className="font-medium text-gray-500">Subject: </span>
                {live?.subject ?? draft.subject}
              </p>
              <pre className="mt-2 whitespace-pre-wrap rounded bg-gray-50 p-3 font-sans text-sm text-gray-800">
                {live?.liveBodyText ?? draft.bodyText}
              </pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
